#!/bin/bash

# @module: core
# @description: Shlib core
# @author: oxfn
# @created: 2016-05-20
# @modified: 2016-05-20

export STATUS_OK=0
export STATUS_ERROR=1

# @function: f_read_line
# @description: Read line from standard input
f_read_line() {
    local _res=""
    read _res
    echo $_res
}

# @function: f_read_char
# @description: Read char from stdin
f_read_char() {
    local _res=""
    read -n 1 _res
    echo $_res
}

