#!/bin/bash

# @module: net
# @description: Shlib net module
# @author: oxfn
# @created: 2016-08-12
# @modified: 2016-08-12

# @function f_curl
# @param url 
# @param method
# @param headers
# @param data
# Execute cURL request
f_curl() {
    local url="$1"
    local method="$2"
    local headers="$3"
    local data="$4"
    curl --verbose -H "$header" -X "$method" --data "$data" "$url"
}

