#!/bin/bash

_cnt=0
_err=0
t_begin() {
    let _cnt++
    let _err=0
    echo -n "Test #$_cnt: $1 "
}
t_err() {
    let _err++
}
t_end() {
    if [ $_err -eq 0 ]; then
        echo PASSED
    else
        echo FAILED
    fi
}

PATH_ROOT=$(dirname $0)
. core
. log

t_begin 'Get current log level'
[ $(f_get_log_level) -eq 0 ] || t_err
t_end

t_begin 'Set current log level to ERROR'
f_set_log_level $LOG_LEVEL_ERROR
[ $(f_get_log_level) -eq 1 ] || t_err
t_end

t_begin 'Log error (level match)'
f_error test 2>/tmp/stderr
[ -e /tmp/stderr ] || t_err
[[ "$(cat /tmp/stderr)" == 'test' ]] || t_err
rm /tmp/stderr
t_end

t_begin 'Log warning (level mismatch)'
f_warn test 2>/tmp/stderr
[ -e /tmp/stderr ] || t_err
[ $(cat /tmp/stderr | wc -c) -eq 0 ] || t_err
rm /tmp/stderr
t_end

